version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
  
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.1
    ports:
      - 12201:12201/udp
    depends_on: 
      - elasticsearch
    volumes: 
      - ./config:/usr/share/logstash/pipeline

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports: 
      - 5601:5601
    depends_on:
      - elasticsearch