version: '3'

services:

  rmq-publisher:
    image: jackvanlightly/rabbitmq-publisher:latest
    environment:
      - MGMT-IP=192.168.233.132
      - MGMT-PORT=15672
      - USER=test
      - PASSWORD=test
      - USE-HTTPS=false
      - VHOST=%2f
      - USE-AMQPROXY=false
      - USE-TOXIPROXY=true
      - BROKER-NAME=rabbitmq1
      - BROKER-IP=toxiproxy
      - BROKER-PORT=5672
      - PUB-MODE=async
      - USE-CONFIRMS=true
      - MSG-COUNT=100000000
      - PRINT-MOD=1000
      - IN-FLIGHT-MAX=10000

  toxiproxy:
    image: shopify/toxiproxy
    hostname: toxiproxy
    container_name: toxiproxy
    ports:
      - 5672:5672
      - 15672:15672
      - 8474:8474