version: "3"
volumes:
  # We'll define a volume that will store the data from the postgres databases:
  rabbit-data:
    driver: local

services:
  amqp:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    healthcheck:
      test: "exit 0"
