version: '3'

services:

  rabbitmq1:
    image: rabbitmq:3.7-management
    hostname: rabbitmq1
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      # - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      # - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      #- RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config

  # rabbitmq2:
  #   image: rabbitmq:3.7-management
  #   hostname: rabbitmq2
  #   depends_on:
  #     - rabbitmq1
  #   environment:
  #     - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
  #   volumes:
  #     - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
  #     - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  #   entrypoint: /usr/local/bin/cluster-entrypoint.sh

  # rabbitmq3:
  #   image: rabbitmq:3.7-management
  #   hostname: rabbitmq3
  #   depends_on:
  #     - rabbitmq1
  #   environment:
  #     - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
  #   volumes:
  #     - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
  #     - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  #   entrypoint: /usr/local/bin/cluster-entrypoint.sh

  amqproxy:
    image: amqproxy
    ports:
      - 5673:5673
    environment:
      - AMQP_URL=amqp://rabbitmq1:5672
    
  # haproxy:
  #   image: haproxy:1.7
  #   volumes:
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  #   depends_on:
  #     - rabbitmq1
  #     - rabbitmq2
  #     - rabbitmq3
  #   ports:
  #     - 15673:15672
  #     - 5672:5672
  #     - 6001:6001
  #     - 6002:6002
  #     - 6003:6003
  #     - 7001:7001
  #     - 7002:7002
  #     - 7003:7003